#!/bin/bash
# Job name:static

# Project:
##SBATCH --account=YourProject
# Wall clock limit:
#SBATCH --time=2400:00:00
#SBATCH --mail-type=end
#SBATCH -N 1

#SBATCH --output=O_deficient.%A_%a.out

#!/bin/bash
ulimit -a
ulimit -l unlimited
ulimit -s unlimited
source /usr/local/bin/intel13.0.sh
export LD_LIBRARY_PATH=/opt/intel/composer_xe_2013.3.163/mkl/lib/intel64/:$LD_LIBRARY_PATH



# folder achitecture :
# P2-P3_project/specie/stacking/jobfolder/O_deficient/job1
# exemple : P2-P3_project/Li/O3/Na05-li033-mn067-o2__O3-0/O_deficient/job1/POSCAR
# Launch an array for each specie ($PWD = P2-P3_project/Li )

echo ${SLURM_ARRAY_TASK_ID}

# (4 dir, 7 jobfolder , 2 O_deficient  each) = 56 jobs

# scan for all stackings dir :
stacking_dir_list=$(ls -d -- */)
stack_arr=(${stacking_dir_list[*]})

folder_number=$((${SLURM_ARRAY_TASK_ID}/14%4))
echo ${folder_number}

stacking_dir_name=${stack_arr[${folder_number}]}
echo ${stacking_dir_name}
cd ${stacking_dir_name}

echo "JOBDIR="$PWD
# scan for all job dir :
job_array=$(ls -d -- */)
job_arr=(${job_array[*]})

job_number=$((${SLURM_ARRAY_TASK_ID}/2%7))
echo $job_number

job_name=${job_arr[${job_number}]}
echo $job_name
cd $job_name

# scan for all O_deficient :
O_def_array=$(ls -d -- O_def*/)
O_def_arr=(${O_def_array[*]})

O_def_number=$((${SLURM_ARRAY_TASK_ID}%2))
echo $O_def_number

O_def_name=${O_def_arr[${O_def_number}]}
echo $O_def_name
cd $O_def_name


echo "JOBDIR="$PWD

touch visited

# cp POSCAR INIT_POSCAR
# mpirun --bind-to-core /home/sol/Vasp/Vasp5/vasp.5.4.1/build/std/vasp > log1
# cp CONTCAR POSCAR
# mpirun --bind-to-core /home/sol/Vasp/Vasp5/vasp.5.4.1/build/std/vasp > log2
# cp POSCAR INIT_2_POSCAR
# cp CONTCAR POSCAR


