#!/bin/bash
# Job name:static

# Project:
##SBATCH --account=YourProject
# Wall clock limit:
#SBATCH --time=2400:00:00
#SBATCH --mail-type=end
#SBATCH -N 1

#SBATCH --output=bader_array.%A_%a.out

#!/bin/bash
source /usr/local/bin/intel18.sh
#export I_MPI_CHECK_DAPL_PROVIDER_MISMATCH=off 
#export I_MPI_FABRICS=shm:tmi 
#export I_MPI_PIN_RESPECT_HCA=1
export I_MPI_PIN=1
ulimit -s unlimited
ulimit -a


array=$(ls -d -- */)
arr=(${array[*]})
echo ${SLURM_ARRAY_TASK_ID}
cd ${arr[${SLURM_ARRAY_TASK_ID}-1]}
echo "BADER JOB"
echo "JOBDIR="$PWD

if test -d $PWD/BADER 
then
    echo "BADER folder already exist"
    echo "we stop to avoid messing things up"
else 
    echo "BADER FOLDER NOT FOUND"
    if test -f $PWD/AECCAR0
    then
        echo "AECCAR0 found : enough data to do bader"
        /home/jvergnet/bin/do_bader > log_bader
        echo "BADER DONE "
    fi
fi