#!/bin/bash
# Job name:static

# Project:
##SBATCH --account=YourProject
# Wall clock limit:
#SBATCH --time=2400:00:00
#SBATCH --mail-type=end
#SBATCH -N 1

#!/bin/bash
ulimit -a
ulimit -l unlimited
ulimit -s unlimited
source /usr/local/bin/intel13.0.sh
export LD_LIBRARY_PATH=/opt/intel/composer_xe_2013.3.163/mkl/lib/intel64/:$LD_LIBRARY_PATH



mpirun --bind-to-core /home/sol/Vasp/Vasp5/vasp.5.4.4/bin/vasp_ncl  > log_NC
# /home/sol/Vasp/Vasp5/vasp.5.3.5-openmpi-nc/vasp  > log_NC

mkdir OK
